#!/usr/bin/env bash
# =============================================================================
#   ██████╗ █████╗  ██████╗██╗  ██╗██╗   ██╗    ███████╗███████╗ ██████╗
#  ██╔════╝██╔══██╗██╔════╝██║  ██║╚██╗ ██╔╝    ██╔════╝██╔════╝██╔════╝
#  ██║     ███████║██║     ███████║ ╚████╔╝     ███████╗█████╗  ██║
#  ██║     ██╔══██║██║     ██╔══██║  ╚██╔╝      ╚════██║██╔══╝  ██║
#  ╚██████╗██║  ██║╚██████╗██║  ██║   ██║       ███████║███████╗╚██████╗
#   ╚═════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝   ╚═╝       ╚══════╝╚══════╝ ╚═════╝
#
#  CachyOS Cybersecurity Optimization Script
#  Fish shell native — does NOT touch your shell choice
#  Version : 1.1.0  |  License : MIT
# Author: cybermaksx 
# =============================================================================

set -euo pipefail
IFS=$'\n\t'

# ──────────────────────────────────────────────────────────────────────────────
# COLOURS
# ──────────────────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

banner() {
cat << 'EOF'
  ┌──────────────────────────────────────────────────────┐
  │           CachyOS  ×  BlackArch  SEC SETUP           │
  │         Automated Cybersecurity Toolkit v1.1         │
  │              Fish shell native edition               │
  └──────────────────────────────────────────────────────┘
EOF
}

info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }
section() { echo -e "\n${BOLD}${BLUE}══ $* ══${NC}"; }

# ──────────────────────────────────────────────────────────────────────────────
# PREFLIGHT
# ──────────────────────────────────────────────────────────────────────────────
preflight() {
    section "Preflight checks"

    if [[ $EUID -eq 0 ]]; then
        error "Do NOT run as root. The script uses sudo internally."
        exit 1
    fi

    if ! command -v pacman &>/dev/null; then
        error "pacman not found – this script targets CachyOS / Arch-based systems."
        exit 1
    fi

    if ! ping -c1 -W3 archlinux.org &>/dev/null; then
        error "No internet connection detected."
        exit 1
    fi

    success "All preflight checks passed."
}

# ──────────────────────────────────────────────────────────────────────────────
# BACKUP /etc/pacman.conf
# ──────────────────────────────────────────────────────────────────────────────
backup_pacman_conf() {
    local backup
    backup="/etc/pacman.conf.bak_$(date +%Y%m%d_%H%M%S)"
    sudo cp /etc/pacman.conf "$backup"
    info "pacman.conf backed up → $backup"
}

# ──────────────────────────────────────────────────────────────────────────────
# ADD BLACKARCH MIRRORS
# ──────────────────────────────────────────────────────────────────────────────
add_blackarch_repo() {
    section "Adding BlackArch repository"

    if grep -q '\[blackarch\]' /etc/pacman.conf; then
        warn "BlackArch repo already present in pacman.conf – skipping."
        return
    fi

    info "Downloading BlackArch strap script..."
    local strap
    strap=$(mktemp /tmp/blackarch-strap.XXXXXX.sh)

    if ! curl -fsSL https://blackarch.org/strap.sh -o "$strap"; then
        error "Failed to download strap.sh"
        rm -f "$strap"
        exit 1
    fi

    # Verify SHA1 checksum published by BlackArch project
    local expected_sha1="5ea40d49ecd14c2e024deecf90605426db97ea0c"
    local actual_sha1
    actual_sha1=$(sha1sum "$strap" | awk '{print $1}')

    if [[ "$actual_sha1" != "$expected_sha1" ]]; then
        error "SHA1 mismatch for strap.sh!"
        error "  Expected : $expected_sha1"
        error "  Got      : $actual_sha1"
        error "Aborting to protect your system."
        rm -f "$strap"
        exit 1
    fi

    chmod +x "$strap"
    sudo bash "$strap"
    rm -f "$strap"

    _write_blackarch_mirrorlist
    success "BlackArch repository added successfully."
}

_write_blackarch_mirrorlist() {
    info "Configuring BlackArch mirror list..."

    sudo tee /etc/pacman.d/blackarch-mirrorlist > /dev/null << 'MIRRORS'
################################################################################
#                       BlackArch Linux Mirror List
#              Generated by cachy-sec-setup v1.1
################################################################################

# Global CDN (primary)
Server = https://mirror.blackarch.org/$repo/os/$arch

# Europe
Server = https://blackarch.unixpeople.org/$repo/os/$arch
Server = https://www.mirrorservice.org/sites/blackarch.org/blackarch/$repo/os/$arch

# Germany
Server = https://ftp.halifax.rwth-aachen.de/blackarch/$repo/os/$arch
Server = https://ftp.gwdg.de/pub/linux/archlinux/blackarch/$repo/os/$arch

# USA
Server = https://mirrors.ocf.berkeley.edu/blackarch/$repo/os/$arch

# Asia
Server = https://mirrors.tuna.tsinghua.edu.cn/blackarch/$repo/os/$arch
MIRRORS

    # Point the [blackarch] section to our mirror list if not already done
    if grep -q '\[blackarch\]' /etc/pacman.conf && \
       ! grep -q 'blackarch-mirrorlist' /etc/pacman.conf; then
        sudo sed -i \
            '/\[blackarch\]/,/^Include/{s|^Include.*|Include = /etc/pacman.d/blackarch-mirrorlist|}' \
            /etc/pacman.conf
    fi

    success "Mirror list configured."
}

# ──────────────────────────────────────────────────────────────────────────────
# SYSTEM UPDATE
# ──────────────────────────────────────────────────────────────────────────────
system_update() {
    section "Full system update"
    sudo pacman -Syyu --noconfirm
    success "System is up to date."
}

# ──────────────────────────────────────────────────────────────────────────────
# INSTALL AUR HELPER (paru preferred, yay fallback)
# ──────────────────────────────────────────────────────────────────────────────
install_aur_helper() {
    section "AUR Helper"

    if command -v paru &>/dev/null; then
        success "paru already installed."
        return
    fi

    if command -v yay &>/dev/null; then
        success "yay already installed – will use as AUR helper."
        return
    fi

    info "Installing paru..."
    sudo pacman -S --noconfirm --needed base-devel git

    local tmpdir
    tmpdir=$(mktemp -d)
    git clone https://aur.archlinux.org/paru.git "$tmpdir/paru"
    (cd "$tmpdir/paru" && makepkg -si --noconfirm)
    rm -rf "$tmpdir"

    success "paru installed."
}

# ──────────────────────────────────────────────────────────────────────────────
# GENERIC CATEGORY INSTALLER
# Tries pacman first, then AUR helper for anything not found.
# ──────────────────────────────────────────────────────────────────────────────
install_category() {
    local category_name="$1"
    shift
    local tools=("$@")
    local failed=()

    section "Installing: $category_name"

    for pkg in "${tools[@]}"; do
        # Strip inline bash comments
        pkg="${pkg%%#*}"
        pkg="${pkg// /}"
        [[ -z "$pkg" ]] && continue

        if pacman -Qi "$pkg" &>/dev/null; then
            info "$pkg already installed – skipping."
            continue
        fi

        info "Installing $pkg ..."
        if sudo pacman -S --noconfirm --needed "$pkg" 2>/dev/null; then
            success "$pkg installed."
        else
            local aur_helper=""
            command -v paru &>/dev/null && aur_helper="paru"
            command -v yay  &>/dev/null && aur_helper="yay"

            if [[ -n "$aur_helper" ]]; then
                if $aur_helper -S --noconfirm --needed "$pkg" 2>/dev/null; then
                    success "$pkg installed via AUR."
                else
                    warn "$pkg – installation failed, skipping."
                    failed+=("$pkg")
                fi
            else
                warn "$pkg not in repos and no AUR helper available – skipping."
                failed+=("$pkg")
            fi
        fi
    done

    if [[ ${#failed[@]} -gt 0 ]]; then
        warn "Failed in '$category_name': ${failed[*]}"
    fi
}

# ──────────────────────────────────────────────────────────────────────────────
# TOOL LISTS  (one package per line, comments allowed after #)
# ──────────────────────────────────────────────────────────────────────────────

RECON_TOOLS=(
    nmap          # Port & service scanner
    masscan       # High-speed port scanner
    rustscan      # Rust-based port scanner
    amass         # DNS & ASN mapping
    subfinder     # Subdomain enumeration
    httprobe      # Probe hosts for HTTP/S
    whatweb       # Web fingerprinting
    theharvester  # OSINT: emails, domains
    netdiscover   # ARP network discovery
    arp-scan      # ARP scanner
    dnsrecon      # DNS reconnaissance
    dnsx          # DNS toolkit
    fierce        # DNS brute-forcer
    shodan        # Shodan CLI client
)

WEB_TOOLS=(
    burpsuite     # Web proxy & scanner
    zaproxy       # OWASP ZAP
    sqlmap        # SQL injection automation
    nikto         # Web server scanner
    gobuster      # Dir/DNS brute-forcer
    ffuf          # Fast web fuzzer
    wfuzz         # Web fuzzer
    dirsearch     # Directory brute-forcer
    nuclei        # Vulnerability scanner
    wafw00f       # WAF fingerprinting
    arjun         # HTTP param discovery
    xsstrike      # XSS exploitation suite
    commix        # Command injection
    wpscan        # WordPress scanner
)

NETWORK_TOOLS=(
    wireshark-qt  # Packet analyser GUI
    tshark        # Packet analyser CLI
    tcpdump       # Packet capture
    ettercap      # MITM framework
    bettercap     # Network attack suite
    mitmproxy     # HTTP MITM proxy
    responder     # LLMNR/NBT-NS poisoner
    netcat        # Swiss-army TCP/UDP tool
    socat         # Multipurpose relay
    hping         # Packet crafting
    scapy         # Python packet library
    proxychains-ng # Chain proxies
    tor           # Onion routing
    openvpn       # VPN client
    wireguard-tools # WireGuard VPN
    iptables      # Firewall rules
    nftables      # Modern firewall
)

EXPLOITATION_TOOLS=(
    metasploit    # Exploitation framework
    exploitdb     # Exploit database + searchsploit
    gdb           # GNU debugger
    pwndbg        # GDB plugin for pwning
    pwntools      # CTF exploit library
    ropper        # ROP gadget finder
    radare2       # Reverse engineering framework
    ghidra        # NSA disassembler suite
    jadx          # DEX/APK decompiler
    checksec      # Binary hardening checker
    ltrace        # Library call tracer
    strace        # Syscall tracer
)

PASSWORD_TOOLS=(
    hashcat       # GPU password cracker
    john          # John the Ripper
    hydra         # Network login brute-forcer
    medusa        # Parallel login brute-forcer
    crunch        # Wordlist generator
    cewl          # Wordlist from web pages
    wordlistctl   # Wordlist downloader
)

WIRELESS_TOOLS=(
    aircrack-ng   # Wi-Fi audit suite
    hcxtools      # Convert/analyse Wi-Fi captures
    hcxdumptool   # Capture PMKIDs/handshakes
    kismet        # Wireless network detector
    bluez         # Bluetooth stack
    bluez-utils   # Bluetooth CLI utilities
)

FORENSICS_TOOLS=(
    autopsy       # Digital forensics GUI
    sleuthkit     # CLI forensic toolkit
    volatility3   # Memory analysis
    foremost      # File carving
    binwalk       # Firmware analysis
    hexedit       # Hex editor
    exiftool      # Metadata tool
    bulk-extractor # Data extraction from images
    dc3dd         # Forensic dd
    guymager      # Forensic disk imager
)

CRYPTO_TOOLS=(
    openssl       # TLS/SSL toolkit
    gnupg         # GPG encryption
    hashdeep      # Recursive hashing
    steghide      # Steganography embed/extract
    zsteg         # PNG/BMP stego detector
    testssl.sh    # TLS server tester
)

SE_TOOLS=(
    set           # Social-Engineer Toolkit
    gophish       # Phishing framework
)

CLOUD_TOOLS=(
    docker        # Container runtime
    docker-compose # Multi-container tool
    kubectl       # Kubernetes CLI
    trivy         # Container vulnerability scanner
    trufflehog    # Secrets scanner in git
    gitleaks      # Git secrets detector
    aws-cli       # AWS CLI
)

OSINT_TOOLS=(
    spiderfoot    # OSINT automation framework
    recon-ng      # Web recon framework
    sherlock      # Username search across platforms
    maltego       # Link analysis / visual OSINT
    photon        # Fast OSINT web scraper
)

UTILITY_TOOLS=(
    python-pip           # Python package manager
    python-virtualenv    # Python venvs
    git                  # Version control
    curl                 # HTTP client
    wget                 # HTTP downloader
    jq                   # JSON processor
    ripgrep              # Fast grep
    fd                   # Fast find
    bat                  # Better cat
    tmux                 # Terminal multiplexer
    fzf                  # Fuzzy finder
    htop                 # System monitor
    neofetch             # System info
    tree                 # Directory tree
    net-tools            # ifconfig, netstat
    iproute2             # ip, ss
    bind                 # dig, nslookup
    whois                # WHOIS client
    traceroute           # Network path tracer
    xxd                  # Hex dump tool
)

# ──────────────────────────────────────────────────────────────────────────────
# PYTHON SECURITY LIBRARIES  (into a venv to avoid pacman conflicts)
# ──────────────────────────────────────────────────────────────────────────────
install_python_libs() {
    section "Python Security Libraries"

    local venv_dir="$HOME/.venvs/sec"

    if [[ ! -d "$venv_dir" ]]; then
        python3 -m venv "$venv_dir"
        info "Created virtualenv at $venv_dir"
    fi

    # shellcheck source=/dev/null
    source "$venv_dir/bin/activate"

    pip install --upgrade pip --quiet

    local py_libs=(
        requests
        httpx
        scapy
        impacket
        pwntools
        paramiko
        cryptography
        pyOpenSSL
        dnspython
        shodan
        censys
        ldap3
        netifaces
        volatility3
        yara-python
        frida-tools
    )

    if pip install --quiet "${py_libs[@]}"; then
        success "Python libraries installed in $venv_dir"
    else
        warn "Some Python libraries may have failed – check manually."
    fi

    deactivate

    # Write a fish activator helper
    _write_fish_venv_helper "$venv_dir"
}

_write_fish_venv_helper() {
    local venv_dir="$1"
    local helper="$HOME/.config/fish/functions/secenv.fish"

    mkdir -p "$(dirname "$helper")"
    cat > "$helper" << FISHFN
function secenv --description 'Activate the security Python venv'
    source $venv_dir/bin/activate.fish
    echo "Security venv active. 'deactivate' to exit."
end
FISHFN
    success "Fish function 'secenv' written → $helper"
}

# ──────────────────────────────────────────────────────────────────────────────
# KERNEL / SYSCTL HARDENING
# ──────────────────────────────────────────────────────────────────────────────
apply_sysctl_hardening() {
    section "Kernel hardening (sysctl)"

    sudo tee /etc/sysctl.d/99-cachy-sec.conf > /dev/null << 'SYSCTL'
# ── CachyOS Security Hardening ─────────────────────────────────────────────

# Disable IP forwarding (re-enable only if routing is needed)
net.ipv4.ip_forward = 0
net.ipv6.conf.all.forwarding = 0

# SYN flood protection
net.ipv4.tcp_syncookies = 1

# Ignore ICMP broadcast ping
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Ignore bogus ICMP error responses
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Reverse path filtering (anti-spoofing)
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Reject source-routed packets
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0

# Reject ICMP redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0

# Do not send ICMP redirects
net.ipv4.conf.all.send_redirects = 0

# Log packets with impossible addresses (martians)
net.ipv4.conf.all.log_martians = 1

# Disable SUID core dumps
fs.suid_dumpable = 0

# Restrict dmesg to root
kernel.dmesg_restrict = 1

# Hide kernel pointers
kernel.kptr_restrict = 2

# Disable magic SysRq
kernel.sysrq = 0

# Restrict ptrace to parent processes only
kernel.yama.ptrace_scope = 1

# TCP time-wait assassination protection
net.ipv4.tcp_rfc1337 = 1

# Full ASLR
kernel.randomize_va_space = 2
SYSCTL

    sudo sysctl --system &>/dev/null
    success "sysctl hardening applied → /etc/sysctl.d/99-cachy-sec.conf"
}

# ──────────────────────────────────────────────────────────────────────────────
# WORKSPACE DIRECTORY STRUCTURE
# ──────────────────────────────────────────────────────────────────────────────
create_workspace() {
    section "Creating workspace"
    local base="$HOME/sec"

    mkdir -p \
        "$base/recon"               \
        "$base/web"                 \
        "$base/network"             \
        "$base/exploitation"        \
        "$base/passwords/wordlists" \
        "$base/wireless"            \
        "$base/forensics"           \
        "$base/malware"             \
        "$base/reports"             \
        "$base/ctf"                 \
        "$base/tools/custom"

    # rockyou – try pacman package first, curl as fallback
    local rockyou_dst="$base/passwords/wordlists/rockyou.txt"
    if [[ ! -f "$rockyou_dst" ]]; then
        if [[ -f /usr/share/wordlists/rockyou.txt ]]; then
            cp /usr/share/wordlists/rockyou.txt "$rockyou_dst"
            success "rockyou.txt copied from system wordlists."
        elif [[ -f /usr/share/wordlists/rockyou.txt.gz ]]; then
            gunzip -c /usr/share/wordlists/rockyou.txt.gz > "$rockyou_dst"
            success "rockyou.txt extracted from system wordlists."
        else
            info "Downloading rockyou.txt ..."
            if curl -fsSL \
                "https://github.com/danielmiessler/SecLists/raw/master/Passwords/Leaked-Databases/rockyou.txt.tar.gz" \
                -o "$base/passwords/wordlists/rockyou.txt.tar.gz" 2>/dev/null \
            && tar -xzf "$base/passwords/wordlists/rockyou.txt.tar.gz" \
                   -C "$base/passwords/wordlists/" \
            && rm -f "$base/passwords/wordlists/rockyou.txt.tar.gz"; then
                success "rockyou.txt downloaded."
            else
                warn "Could not download rockyou.txt – grab it manually later."
            fi
        fi
    else
        info "rockyou.txt already present – skipping."
    fi

    success "Workspace ready at $base"
}

# ──────────────────────────────────────────────────────────────────────────────
# FISH SHELL CONFIGURATION
# Writes aliases into ~/.config/fish/conf.d/sec_aliases.fish
# Does NOT change the user's shell.
# ──────────────────────────────────────────────────────────────────────────────
configure_fish() {
    section "Fish shell – security aliases"

    local fish_conf_dir="$HOME/.config/fish/conf.d"
    local alias_file="$fish_conf_dir/sec_aliases.fish"

    mkdir -p "$fish_conf_dir"

    cat > "$alias_file" << 'FISHALIASES'
# ─────────────────────────────────────────────────────────────────────────────
# CachyOS Security Aliases  –  loaded automatically by fish
# Generated by cachy-sec-setup v1.1
# ─────────────────────────────────────────────────────────────────────────────

# ── Workspace navigation ─────────────────────────────────────────────────────
abbr --add sec   'cd ~/sec'
abbr --add recon 'cd ~/sec/recon'
abbr --add ctf   'cd ~/sec/ctf'

# ── Network ──────────────────────────────────────────────────────────────────
abbr --add myip      'curl -s ifconfig.me'
abbr --add localip   'ip -br a'
abbr --add listening 'ss -tlnp'
abbr --add ports     'ss -tulpn'
abbr --add sniff     'sudo tcpdump -i any -nn -v'

# ── Nmap templates ───────────────────────────────────────────────────────────
abbr --add nmap-quick   'nmap -T4 -F'
abbr --add nmap-full    'nmap -T4 -p- -sV -sC -O'
abbr --add nmap-udp     'sudo nmap -sU -T4 --top-ports 200'
abbr --add nmap-vuln    'nmap --script=vuln -T4'
abbr --add nmap-stealth 'sudo nmap -sS -T2 -p-'

# ── Web ──────────────────────────────────────────────────────────────────────
abbr --add ww           'whatweb -a 3'
abbr --add ds-quick     'dirsearch -w /usr/share/wordlists/dirb/common.txt'
abbr --add ffuf-dir     'ffuf -w /usr/share/wordlists/dirb/common.txt -u'

# ── Passwords ────────────────────────────────────────────────────────────────
set -gx ROCKYOU "$HOME/sec/passwords/wordlists/rockyou.txt"
abbr --add hashid 'hashcat --identify'

# ── Proxy / Tor ──────────────────────────────────────────────────────────────
abbr --add pchain    'proxychains4 -q'
abbr --add tor-check 'curl -s https://check.torproject.org/api/ip | jq'

# ── Metasploit ───────────────────────────────────────────────────────────────
abbr --add msfgo 'msfconsole -q'

# ── Encoding helpers (as functions, not abbr, to accept args) ─────────────────
function b64d   --description 'Base64 decode'  ; echo $argv | base64 -d  ; end
function b64e   --description 'Base64 encode'  ; echo $argv | base64     ; end
function urld   --description 'URL decode'
    python3 -c "import sys,urllib.parse;print(urllib.parse.unquote(sys.argv[1]))" $argv
end
function urle   --description 'URL encode'
    python3 -c "import sys,urllib.parse;print(urllib.parse.quote(sys.argv[1]))"  $argv
end
function hex2text --description 'Hex → ASCII' ; echo $argv | xxd -r -p   ; end
function text2hex --description 'ASCII → Hex' ; echo $argv | xxd -p      ; end

# ── Grep extractors ──────────────────────────────────────────────────────────
function extract-ips --description 'Print all IPv4 addresses from stdin'
    grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b'
end
function extract-urls --description 'Print all URLs from stdin'
    grep -oE 'https?://[^\s/$.?#][^\s]*'
end
function extract-emails --description 'Print all emails from stdin'
    grep -oE '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
end

# ── GDB quiet ────────────────────────────────────────────────────────────────
abbr --add gdb 'gdb -q'

# ── System updates ───────────────────────────────────────────────────────────
abbr --add update    'sudo pacman -Syyu'
abbr --add ba-update 'sudo pacman -Syyu'

FISHALIASES

    success "Fish aliases written → $alias_file"
    info "They will load automatically on next fish session."
}

# ──────────────────────────────────────────────────────────────────────────────
# ENABLE SYSTEMD SERVICES
# ──────────────────────────────────────────────────────────────────────────────
enable_services() {
    section "Enabling services"

    local services=(tor docker)

    for svc in "${services[@]}"; do
        if systemctl list-unit-files "${svc}.service" &>/dev/null; then
            if sudo systemctl enable --now "$svc" 2>/dev/null; then
                success "$svc enabled & started."
            else
                warn "Could not enable $svc – it may need manual setup."
            fi
        else
            warn "$svc service unit not found – skipping."
        fi
    done

    if getent group docker &>/dev/null; then
        sudo usermod -aG docker "$USER"
        info "Added $USER to docker group (re-login required)."
    fi
}

# ──────────────────────────────────────────────────────────────────────────────
# SUMMARY
# ──────────────────────────────────────────────────────────────────────────────
print_summary() {
    section "Setup Complete"

    echo -e "${GREEN}"
    cat << 'SUMMARY'
  ╔══════════════════════════════════════════════════╗
  ║           Setup Completed Successfully!          ║
  ╚══════════════════════════════════════════════════╝
SUMMARY
    echo -e "${NC}"

    echo -e "${BOLD}What was done:${NC}"
    echo "  ✔ BlackArch mirrors added & verified"
    echo "  ✔ 100+ security tools installed"
    echo "  ✔ Python sec venv at ~/.venvs/sec"
    echo "  ✔ sysctl kernel hardening applied"
    echo "  ✔ Workspace created at ~/sec"
    echo "  ✔ Fish aliases at ~/.config/fish/conf.d/sec_aliases.fish"
    echo ""
    echo -e "${BOLD}Quick start (open a new fish session):${NC}"
    echo "  nmap-quick <target>   – fast port scan"
    echo "  nmap-full  <target>   – full service scan"
    echo "  msfgo                 – Metasploit"
    echo "  secenv                – activate Python sec venv"
    echo "  myip                  – your public IP"
    echo ""
    echo -e "${YELLOW}  Use these tools ONLY on systems you own"
    echo -e "  or have explicit written permission to test.${NC}"
    echo ""
}

# ──────────────────────────────────────────────────────────────────────────────
# USAGE / ARGUMENT PARSING
# ──────────────────────────────────────────────────────────────────────────────
usage() {
    cat << 'USAGE'
Usage: cachy-sec-setup.sh [option]

Options:
  --all           Install everything (default)
  --mirrors       BlackArch mirrors only
  --recon         Reconnaissance tools
  --web           Web application testing tools
  --network       Network / MITM tools
  --exploitation  Exploitation & reversing tools
  --passwords     Password attack tools
  --wireless      Wireless audit tools
  --forensics     Forensics & DFIR tools
  --crypto        Crypto & steganography tools
  --se            Social engineering tools
  --cloud         Cloud & container security
  --osint         OSINT tools
  --utils         Developer utilities
  --python        Python security libraries only
  --harden        Kernel sysctl hardening only
  --fish          Fish shell aliases only
  --help          Show this help
USAGE
    exit 0
}

# ──────────────────────────────────────────────────────────────────────────────
# MAIN
# ──────────────────────────────────────────────────────────────────────────────
main() {
    clear
    banner

    local mode="${1:---all}"

    [[ "$mode" == "--help" || "$mode" == "-h" ]] && usage

    preflight
    backup_pacman_conf

    case "$mode" in
        --mirrors)
            add_blackarch_repo
            ;;
        --harden)
            apply_sysctl_hardening
            ;;
        --fish)
            configure_fish
            ;;
        --python)
            install_python_libs
            ;;
        --recon)
            add_blackarch_repo; system_update; install_aur_helper
            install_category "Reconnaissance" "${RECON_TOOLS[@]}"
            ;;
        --web)
            add_blackarch_repo; system_update; install_aur_helper
            install_category "Web Application" "${WEB_TOOLS[@]}"
            ;;
        --network)
            add_blackarch_repo; system_update; install_aur_helper
            install_category "Network" "${NETWORK_TOOLS[@]}"
            ;;
        --exploitation)
            add_blackarch_repo; system_update; install_aur_helper
            install_category "Exploitation" "${EXPLOITATION_TOOLS[@]}"
            ;;
        --passwords)
            add_blackarch_repo; system_update; install_aur_helper
            install_category "Password Attacks" "${PASSWORD_TOOLS[@]}"
            ;;
        --wireless)
            add_blackarch_repo; system_update; install_aur_helper
            install_category "Wireless" "${WIRELESS_TOOLS[@]}"
            ;;
        --forensics)
            add_blackarch_repo; system_update; install_aur_helper
            install_category "Forensics" "${FORENSICS_TOOLS[@]}"
            ;;
        --crypto)
            add_blackarch_repo; system_update; install_aur_helper
            install_category "Crypto & Stego" "${CRYPTO_TOOLS[@]}"
            ;;
        --se)
            add_blackarch_repo; system_update; install_aur_helper
            install_category "Social Engineering" "${SE_TOOLS[@]}"
            ;;
        --cloud)
            add_blackarch_repo; system_update; install_aur_helper
            install_category "Cloud & Container" "${CLOUD_TOOLS[@]}"
            ;;
        --osint)
            add_blackarch_repo; system_update; install_aur_helper
            install_category "OSINT" "${OSINT_TOOLS[@]}"
            ;;
        --utils)
            add_blackarch_repo; system_update; install_aur_helper
            install_category "Utilities" "${UTILITY_TOOLS[@]}"
            ;;
        --all)
            add_blackarch_repo
            system_update
            install_aur_helper

            install_category "Reconnaissance"    "${RECON_TOOLS[@]}"
            install_category "Web Application"   "${WEB_TOOLS[@]}"
            install_category "Network"           "${NETWORK_TOOLS[@]}"
            install_category "Exploitation"      "${EXPLOITATION_TOOLS[@]}"
            install_category "Password Attacks"  "${PASSWORD_TOOLS[@]}"
            install_category "Wireless"          "${WIRELESS_TOOLS[@]}"
            install_category "Forensics"         "${FORENSICS_TOOLS[@]}"
            install_category "Crypto & Stego"    "${CRYPTO_TOOLS[@]}"
            install_category "Social Eng."       "${SE_TOOLS[@]}"
            install_category "Cloud & Container" "${CLOUD_TOOLS[@]}"
            install_category "OSINT"             "${OSINT_TOOLS[@]}"
            install_category "Utilities"         "${UTILITY_TOOLS[@]}"

            install_python_libs
            apply_sysctl_hardening
            create_workspace
            configure_fish
            enable_services
            ;;
        *)
            error "Unknown option: $mode"
            usage
            ;;
    esac

    print_summary
}

main "$@"
